#! /bin/sh

NAME=onedrive
PIDFILE=/run/onedrive/$NAME.pid
DESC="Onedrive (abraunegg) sysv service"
DAEMON=/usr/local/bin/onedrive

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

start() {
  log_daemon_msg "ABOUT TO START $DESC" "$NAME"
  export HOME=/home/kenny
  runuser -u kenny -- /usr/local/bin/onedrive --monitor &
  
  if [ -e $PIDFILE ]; then
    if $0 status > /dev/null ; then
      log_success_msg "$DESC already started; not starting"
      return
    else
      log_success_msg "Removing stale PID file $PIDFILE"
      rm -f $PIDFILE
    fi
  fi

  mkdir -p `dirname "$PIDFILE"`
  echo $! > $PIDFILE
  log_success_msg "$NAME service started"
}

stop() {
  log_daemon_msg "Stopping $DESC" "$NAME"
  start-stop-daemon --stop --retry 5 --quiet --oknodo --pidfile $PIDFILE
  log_end_msg $?
  rm -f $PIDFILE
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status_of_proc -p $PIDFILE "$DAEMON" onedrive
    ;;
  restart|reload|condrestart)
    stop
    start
    ;;
  *)
    echo Don\'t recognize command \'$1\'
    exit 2
    ;;
esac
