#! /bin/sh

NAME=onedrive

test -x /usr/local/bin/onedrive || exit 0

start() {
  echo ABOUT TO START
}

stop() {
  echo ABOUT TO STOP
}

status() {
  echo STATUS
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart|reload|condrestart)
    stop
    start
    ;;
  *)
    echo Don\'t recognize command \'$1\'
    exit 1
esac
