#! /bin/sh

NAME=onedrive
PIDFILE=/run/onedrive/$NAME.pid
DESC="Onedrive (abraunegg) sysv service"
DAEMON=/usr/local/bin/onedrive

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

dummy() {
  echo Home is $HOME
  echo I am `whoami`
}

start() {
  log_daemon_msg "ABOUT TO START $DESC" "$NAME"
  export HOME=/home/kenny
  runuser -u kenny -- /usr/local/bin/onedrive --monitor &
  echo STARTED
}

stop() {
  echo ABOUT TO STOP
}

status() {
  echo STATUS
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart|reload|condrestart)
    stop
    start
    ;;
  *)
    echo Don\'t recognize command \'$1\'
    exit 1
esac
